### ISSUE TITLE
Add Device Endpoint doesn't allow for an empty year manufactured value

### ISSUE THREAD

**Issue by AshlynAdamson** [cs481-ekh/s22-beima#299]
If the user doesn't put anything in the year manufactured field, then submits a new device, the request will be 400, indicating a bad request. This is because the endpoint cannot convert a null to a System.Int32 type.

**Steps to Reproduce:**
1. Navigate to Add Device Page
2. Select a Device Type
3. Select Add Device with empty fields
4. Notice the device with empty fields is not added to the database and the response is 400 from the endpoint

**Actual Results:**
Empty device is not added

**Expected Results:**
Empty fields should be allowed, therefore an empty device should be added to the database

**Comment by roguedeleter** [comment]
This bug has not been fixed, the backend is still rejecting null "yearManufactured" inputs.
