### ISSUE TITLE
Updated build settings to run the application from a subdirectory and not root.

### ISSUE THREAD

**Issue by Kenny-Miller** [cs481-ekh/s22-beima#417]
References user story #278
Since the sdp server will not allow us to run our frontend from root, we must make sure that it can be ran from a sub directory.
ex instead of https://sdp.../devices it should be https://sdp.../beima/devices

Should be tested by deploying and testing on the sdp server.

**Comment by thessbsu** [comment]
emailing Dr. Henderson to confirm whether this will be needed if we are not serving from a /wwwroot directory like a standard webpage since all paths should be the same since they're on an independent directory structure inside the container

**Comment by thessbsu** [comment]
confirmed container does not need anything special done on build since it's like running it in a vm

**Comment by thessbsu** [comment]
not working in deploy env, Henderson says likely because it's served at http://host/beima.
need to update config and see if it fixes it
